### ISSUE TITLE
Fix / Replace current Emoji Picker

### ISSUE THREAD

**Issue by Marak** [Marak/buddypond#1]
We like the current emoji picker ( https://github.com/woody180/vanilla-javascript-emoji-picker ) but are experiencing some performance issues with our current usage.

The desktop currently requires 20x emoji picker binds on load for creating 10 pond windows + 10 chat windows. This isn't ideal due to the amount of code required for each emoji instance.

It would be better if we could dynamically bind / unbind the emoji picker on window load, or perhaps use just ONE single EmojiPicker instance and have it be intelligent enough to have context on which textarea it needs to insert into. I couldn't find an easy way to unbind the current EmojiPicker class and I think using a single instance is better solution anyway.

Overall not a super complicated Issue to tackle, but it will require some investigation and work.

**Comment by Deividy** [comment]
how about the emoji picker be an app? can live on the dock and its kind of cool... it could copy the emoji when clicking if there is no textarea active
