### ISSUE TITLE
HOW DO I INTEGRATE MY NFT WALLET WITH THIS APP

### ISSUE THREAD

**Issue by guesant** [Marak/buddypond#17]
HELLO I WANNA SHOW MY NFT S THAT I """"OWN"""" ON MY PROFILE, I WANNA THAT EVERYONE KNOWS THAT I OWNS IT 

WHY THIS aPP IS WEB 3 BYT NOT HAVE INTEGRATION WITH BITCOIN ????

**Comment by Marak** [comment]
Hello @guesant 

Thank you for your contribution.

We'd like to see an NFT gallery option. We think it would be neat.

Please feel free to open a Pull Request to add this functionality and we will gladly merge it.

Closing and locking.
