### ISSUE TITLE
Add linting files

### ISSUE THREAD

**Issue by fzn0x** [Marak/buddypond#27]
This will handled by core devops team

**Comment by bl0cknumber** [comment]
We can run the linter on push

**Comment by bl0cknumber** [comment]
This issue was created due to buddies magic code editor that's unrespectedfully

**Comment by Marak** [comment]
The thing is I'm just going to forget to run the linter or it's just going to slow me down. Then I'll have to like lint the entire codebase. Seems like work.

If you could just do your best to not accidentally reformat 800 lines of unrelated code in your Pull Requests I'll think we'll be good. Just stick to the common themes for spacing and tabs. Everything else is basically optional.
