### ISSUE TITLE
Youtube smartlinks should work for all youtube url formats

### ISSUE THREAD

**Issue by Marak** [Marak/buddypond#34]
Right now we only support one YT link style like:

https://www.youtube.com/watch?v=v1K4EAXe2oo

We also need to support links like this: 

https://youtu.be/v1K4EAXe2oo?t=26

( Notice it's a shortened URL and also it has time embed _

**Comment by mardub1635** [comment]
I am working on it. Hopefully will have smtg this week.

**Comment by mardub1635** [comment]
Ok I need help:
This line:

https://github.com/Marak/buddypond/blob/64ca2b5c209754c96e8ee0e6ae692899aafb6540/desktop.js#L540

This is what triggers the Interdimensional Cable window to open right? When I send just an ID to it, for instance "v1K4EAXe2oo" it works. But if I send an ID with its time, for instance "v1K4EAXe2oo?t=26" then the video cannot be found.
[
<img width="1003" alt="Screenshot 2022-03-22 at 20 21 45" src="https://user-images.githubusercontent.com/13570586/159565750-f778c195-561f-4369-a6e1-172fc49b19bd.png">
](url)
I feel like something somewhere else in some other part of the code needs to be changed . But I don't know where to look for. Any input on that?

**Comment by Marak** [comment]
This looks like it may be known CORS issue with youtube and some youtube videos don't work on localhost.

Try a few other videos or try using domain entry in local `/etc/hosts` file.

**Comment by mardub1635** [comment]
Just made the PR

**Comment by Marak** [comment]
Thanks @mardub1635 !!!

Merged.

We still don't seem to support this format thou: `https://www.youtube.com/watch?v=8JgxMVMBESY&t=33s`

**Comment by mardub1635** [comment]
I did not know this format existed. Thanks.
One question though, in which context do you get such link? The only time I get started links on youtube is because I click on the "shared" button and it always give me the short youtu.be version.

**Comment by Marak** [comment]
Not sure of the context.

The format is valid and should be supported.

Will keep this issue open for now. Thanks again for your contributions.

**Comment by mardub1635** [comment]
No need to, I did the PR it is solved.
