### ISSUE TITLE
Uncaught ReferenceError: desktop is not defined (buddypond.js:91)

### ISSUE THREAD

**Issue by figital** [Marak/buddypond#70]
From SDK page try to run buddy.sendMessage()

Error kills page (could have been caught I supposed on SDK page) ...

`Uncaught ReferenceError: desktop is not defined`

thrown from this line ...

`geoflag: desktop.settings.geo_flag_hidden`

i'll see if i can paste a screenshot.

**Comment by figital** [comment]
![image](https://user-images.githubusercontent.com/10073/163070633-de8fb97a-24e1-4357-9120-f89482fa4a7b.png)

**Comment by Marak** [comment]
Good catch @figital 

Thank you for your contributions

This should be resolved now. We added the missing `desktop.settings` scope to the sdk client page.

Haven't been using the SDK Client testing page much in the past month. Please open a PR if you can improve it. Thanks.

**Comment by figital** [comment]
will do @Marak. this would have been an easy one to fix. am strapped for time and perhaps a little PR gun shy. i'll find something small to get started with though soon.
