### ISSUE TITLE
Lazy loading broke build for `file://` Cloud Desktop loading

### ISSUE THREAD

**Issue by Marak** [Marak/buddypond#9]
Switching over to the lazy loading system is causing cors issues when trying to load the Cloud Desktop from the `file://` protocol.

There isn't much we can do to fix that. Same story with trying to do webrtc cameras.

The best solution is to create a new `local.html` file which contains basically the same contents as `index.html` except it performs sync load on boot and doesn't include Apps like `videochat`.

**Comment by Marak** [comment]
Yeah, we discussed it shortly and there isn't much we will do about this right now.

We've got the `desktop.loaded` scope which keeps track of all remotely fetched assets and HTML fragments. We can call into this scope anytime to generate a static `local.html` file for portable builds of Buddy Pond.

I've updated the ReadMe to reflect the change. We can revisit this in the future.

**Comment by guesant** [comment]
WOW! THAT'S SO WEB 3!
